apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:rwm17ujUiD1b/lICkZRNka8OB+hc7iibnKmDn3sfgx3kMWvUBAYPQ6gZACWWQcW6TK/dqhJy3hkon3Z7c2RzG8rLgfYZO4zhlEcVEDfw57m73o9UeOi3yK2L7t6VAfprnWUIyH46zze69y5dgk+MGmKjDHZSMOGia9OWA+u56bI5iv83rusdZ8gd52JzGuaHAytHgee/ytwmR/uPnbhs7wfkm1p8Blr/Uq2Lxwm0Q4zpOlz7XAtqKLMkYqYNZxdDJX09l3qRf4yi5fMddFBDNrub5dAfz+P9jXZgliwCePE9x8dKpmPV4WSTskI=,iv:RolG/2+pd5t7eimPqQ/m0+nJiilX+xjj80v8EC1WWu0=,tag:xoSRIHko1Y1rkrPinGM/aQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1ns2ht3w63dktctjqcqf3hs4ctxqztywa8v644rx9s5nq0kgug9tsad2z75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMmR2ME5BTW8xR0NRckNV
            emRrRlJJZWtTcU9WVmZzWm9CK0diVHpXYkdVCklDTUttZUgzNjZNdVlmY1NSa2p4
            QWRITUlsemk5aTczZGdPV3U4bzRlTjQKLS0tIGp1Z0RqTkRacUlDdnhycFB5c0Zh
            R0xLUUFOU2Q0MW9WbVFhbmJUWW9YeVEKooZa4U4gL2fMJgRr00w/axIOP7f7ZHUA
            Vz+pbqZUlzdyzJv6x0I4mgHya+29v5eBNqETYQgwlzjhgQ7vJPFhFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T15:05:07Z"
    mac: ENC[AES256_GCM,data:0sHmhWLrUGHe12CISdM3Exv3KnSPLkLFFbLQa3sltP/aio/4j6gAObo6cqKvmXYWmV47Dbl16Tdz/EixU3q3OXKaPFrP11zvZNkFaDawmC2VdbKYW3D2BNu+S9BMUS7Z2AdbffzPerjcKZki2+Bt3LC5pwq02jlVJZ7d8ZCQrvU=,iv:ubH3hUPINpjS7/oKfGJlu0rQuMVBNLfbxAhXQ6qBzwI=,tag:lY1C70yuNF1+U3s1QNmJcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
